//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace KinetikV1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class kinetikEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new kinetikEntities object using the connection string found in the 'kinetikEntities' section of the application configuration file.
        /// </summary>
        public kinetikEntities() : base("name=kinetikEntities", "kinetikEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new kinetikEntities object.
        /// </summary>
        public kinetikEntities(string connectionString) : base(connectionString, "kinetikEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new kinetikEntities object.
        /// </summary>
        public kinetikEntities(EntityConnection connection) : base(connection, "kinetikEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<commerce> commerces
        {
            get
            {
                if ((_commerces == null))
                {
                    _commerces = base.CreateObjectSet<commerce>("commerces");
                }
                return _commerces;
            }
        }
        private ObjectSet<commerce> _commerces;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<log> logs
        {
            get
            {
                if ((_logs == null))
                {
                    _logs = base.CreateObjectSet<log>("logs");
                }
                return _logs;
            }
        }
        private ObjectSet<log> _logs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<offer> offers
        {
            get
            {
                if ((_offers == null))
                {
                    _offers = base.CreateObjectSet<offer>("offers");
                }
                return _offers;
            }
        }
        private ObjectSet<offer> _offers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<account> accounts
        {
            get
            {
                if ((_accounts == null))
                {
                    _accounts = base.CreateObjectSet<account>("accounts");
                }
                return _accounts;
            }
        }
        private ObjectSet<account> _accounts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<setting> settings
        {
            get
            {
                if ((_settings == null))
                {
                    _settings = base.CreateObjectSet<setting>("settings");
                }
                return _settings;
            }
        }
        private ObjectSet<setting> _settings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<session> sessions
        {
            get
            {
                if ((_sessions == null))
                {
                    _sessions = base.CreateObjectSet<session>("sessions");
                }
                return _sessions;
            }
        }
        private ObjectSet<session> _sessions;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the commerces EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocommerces(commerce commerce)
        {
            base.AddObject("commerces", commerce);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the logs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTologs(log log)
        {
            base.AddObject("logs", log);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the offers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTooffers(offer offer)
        {
            base.AddObject("offers", offer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the accounts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaccounts(account account)
        {
            base.AddObject("accounts", account);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the settings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosettings(setting setting)
        {
            base.AddObject("settings", setting);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sessions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosessions(session session)
        {
            base.AddObject("sessions", session);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kinetikModel", Name="account")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class account : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new account object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static account Createaccount(global::System.Int64 id)
        {
            account account = new account();
            account.id = id;
            return account;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String category
        {
            get
            {
                return _category;
            }
            set
            {
                OncategoryChanging(value);
                ReportPropertyChanging("category");
                _category = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("category");
                OncategoryChanged();
            }
        }
        private global::System.String _category;
        partial void OncategoryChanging(global::System.String value);
        partial void OncategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String logo
        {
            get
            {
                return _logo;
            }
            set
            {
                OnlogoChanging(value);
                ReportPropertyChanging("logo");
                _logo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("logo");
                OnlogoChanged();
            }
        }
        private global::System.String _logo;
        partial void OnlogoChanging(global::System.String value);
        partial void OnlogoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> created
        {
            get
            {
                return _created;
            }
            set
            {
                OncreatedChanging(value);
                ReportPropertyChanging("created");
                _created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("created");
                OncreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _created;
        partial void OncreatedChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kinetikModel", Name="commerce")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class commerce : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new commerce object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static commerce Createcommerce(global::System.Int64 id)
        {
            commerce commerce = new commerce();
            commerce.id = id;
            return commerce;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String detail
        {
            get
            {
                return _detail;
            }
            set
            {
                OndetailChanging(value);
                ReportPropertyChanging("detail");
                _detail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("detail");
                OndetailChanged();
            }
        }
        private global::System.String _detail;
        partial void OndetailChanging(global::System.String value);
        partial void OndetailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fulfillmentStatus
        {
            get
            {
                return _fulfillmentStatus;
            }
            set
            {
                OnfulfillmentStatusChanging(value);
                ReportPropertyChanging("fulfillmentStatus");
                _fulfillmentStatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("fulfillmentStatus");
                OnfulfillmentStatusChanged();
            }
        }
        private global::System.String _fulfillmentStatus;
        partial void OnfulfillmentStatusChanging(global::System.String value);
        partial void OnfulfillmentStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private Nullable<global::System.DateTime> _date;
        partial void OndateChanging(Nullable<global::System.DateTime> value);
        partial void OndateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String checkoutId
        {
            get
            {
                return _checkoutId;
            }
            set
            {
                OncheckoutIdChanging(value);
                ReportPropertyChanging("checkoutId");
                _checkoutId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("checkoutId");
                OncheckoutIdChanged();
            }
        }
        private global::System.String _checkoutId;
        partial void OncheckoutIdChanging(global::System.String value);
        partial void OncheckoutIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kinetikModel", Name="log")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class log : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new log object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static log Createlog(global::System.Int64 id)
        {
            log log = new log();
            log.id = id;
            return log;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String source
        {
            get
            {
                return _source;
            }
            set
            {
                OnsourceChanging(value);
                ReportPropertyChanging("source");
                _source = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("source");
                OnsourceChanged();
            }
        }
        private global::System.String _source;
        partial void OnsourceChanging(global::System.String value);
        partial void OnsourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String content
        {
            get
            {
                return _content;
            }
            set
            {
                OncontentChanging(value);
                ReportPropertyChanging("content");
                _content = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("content");
                OncontentChanged();
            }
        }
        private global::System.String _content;
        partial void OncontentChanging(global::System.String value);
        partial void OncontentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private Nullable<global::System.DateTime> _date;
        partial void OndateChanging(Nullable<global::System.DateTime> value);
        partial void OndateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kinetikModel", Name="offer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class offer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new offer object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="accountId">Initial value of the accountId property.</param>
        public static offer Createoffer(global::System.Int64 id, global::System.Int64 accountId)
        {
            offer offer = new offer();
            offer.id = id;
            offer.accountId = accountId;
            return offer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> start
        {
            get
            {
                return _start;
            }
            set
            {
                OnstartChanging(value);
                ReportPropertyChanging("start");
                _start = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("start");
                OnstartChanged();
            }
        }
        private Nullable<global::System.DateTime> _start;
        partial void OnstartChanging(Nullable<global::System.DateTime> value);
        partial void OnstartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> end
        {
            get
            {
                return _end;
            }
            set
            {
                OnendChanging(value);
                ReportPropertyChanging("end");
                _end = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("end");
                OnendChanged();
            }
        }
        private Nullable<global::System.DateTime> _end;
        partial void OnendChanging(Nullable<global::System.DateTime> value);
        partial void OnendChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imageUrl
        {
            get
            {
                return _imageUrl;
            }
            set
            {
                OnimageUrlChanging(value);
                ReportPropertyChanging("imageUrl");
                _imageUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imageUrl");
                OnimageUrlChanged();
            }
        }
        private global::System.String _imageUrl;
        partial void OnimageUrlChanging(global::System.String value);
        partial void OnimageUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String offerType
        {
            get
            {
                return _offerType;
            }
            set
            {
                OnofferTypeChanging(value);
                ReportPropertyChanging("offerType");
                _offerType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("offerType");
                OnofferTypeChanged();
            }
        }
        private global::System.String _offerType;
        partial void OnofferTypeChanging(global::System.String value);
        partial void OnofferTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String stores
        {
            get
            {
                return _stores;
            }
            set
            {
                OnstoresChanging(value);
                ReportPropertyChanging("stores");
                _stores = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("stores");
                OnstoresChanged();
            }
        }
        private global::System.String _stores;
        partial void OnstoresChanging(global::System.String value);
        partial void OnstoresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String text
        {
            get
            {
                return _text;
            }
            set
            {
                OntextChanging(value);
                ReportPropertyChanging("text");
                _text = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("text");
                OntextChanged();
            }
        }
        private global::System.String _text;
        partial void OntextChanging(global::System.String value);
        partial void OntextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String demog
        {
            get
            {
                return _demog;
            }
            set
            {
                OndemogChanging(value);
                ReportPropertyChanging("demog");
                _demog = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("demog");
                OndemogChanged();
            }
        }
        private global::System.String _demog;
        partial void OndemogChanging(global::System.String value);
        partial void OndemogChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String method
        {
            get
            {
                return _method;
            }
            set
            {
                OnmethodChanging(value);
                ReportPropertyChanging("method");
                _method = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("method");
                OnmethodChanged();
            }
        }
        private global::System.String _method;
        partial void OnmethodChanging(global::System.String value);
        partial void OnmethodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String offerDetail
        {
            get
            {
                return _offerDetail;
            }
            set
            {
                OnofferDetailChanging(value);
                ReportPropertyChanging("offerDetail");
                _offerDetail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("offerDetail");
                OnofferDetailChanged();
            }
        }
        private global::System.String _offerDetail;
        partial void OnofferDetailChanging(global::System.String value);
        partial void OnofferDetailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private Nullable<global::System.DateTime> _date;
        partial void OndateChanging(Nullable<global::System.DateTime> value);
        partial void OndateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 accountId
        {
            get
            {
                return _accountId;
            }
            set
            {
                OnaccountIdChanging(value);
                ReportPropertyChanging("accountId");
                _accountId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("accountId");
                OnaccountIdChanged();
            }
        }
        private global::System.Int64 _accountId;
        partial void OnaccountIdChanging(global::System.Int64 value);
        partial void OnaccountIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kinetikModel", Name="session")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class session : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new session object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="accountId">Initial value of the accountId property.</param>
        public static session Createsession(global::System.Int64 id, global::System.Int64 accountId)
        {
            session session = new session();
            session.id = id;
            session.accountId = accountId;
            return session;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 accountId
        {
            get
            {
                return _accountId;
            }
            set
            {
                OnaccountIdChanging(value);
                ReportPropertyChanging("accountId");
                _accountId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("accountId");
                OnaccountIdChanged();
            }
        }
        private global::System.Int64 _accountId;
        partial void OnaccountIdChanging(global::System.Int64 value);
        partial void OnaccountIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private Nullable<global::System.DateTime> _date;
        partial void OndateChanging(Nullable<global::System.DateTime> value);
        partial void OndateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String hash
        {
            get
            {
                return _hash;
            }
            set
            {
                OnhashChanging(value);
                ReportPropertyChanging("hash");
                _hash = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("hash");
                OnhashChanged();
            }
        }
        private global::System.String _hash;
        partial void OnhashChanging(global::System.String value);
        partial void OnhashChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kinetikModel", Name="setting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class setting : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new setting object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static setting Createsetting(global::System.Int64 id)
        {
            setting setting = new setting();
            setting.id = id;
            return setting;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String key
        {
            get
            {
                return _key;
            }
            set
            {
                OnkeyChanging(value);
                ReportPropertyChanging("key");
                _key = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("key");
                OnkeyChanged();
            }
        }
        private global::System.String _key;
        partial void OnkeyChanging(global::System.String value);
        partial void OnkeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private global::System.String _value;
        partial void OnvalueChanging(global::System.String value);
        partial void OnvalueChanged();

        #endregion
    
    }

    #endregion
    
}
